### ISSUE TITLE
Cutscene Skip spams chat on attempt

### ISSUE THREAD

**Issue by Ty0sMatic** [NightmareXIV/TextAdvance#15]
It does still work, however my chat spams some error whenever it does:

Attempted to read or write protected memory. This is often an indication that other memory is corrupt.   at ClickLib.Bases.ClickBase`2.ClickAddonList(PopupMenu* popupMenu, UInt16 index, EventType type) in C:\VS\TextAdvance\ClickLib\ClickLib\Bases\ClickBase{TImpl,TStruct}.cs:line 133
   at TextAdvance.ThrottleManager.Throttle(Action a, Int64 delay) in 
C:\VS\TextAdvance\ClickLib\ClickLib\Bases\ClickBase{TImpl,TStruct}.cs:line 133
   at TextAdvance.ThrottleManager.Throttle(Action a, Int64 delay) in C:\VS\TextAdvance\TextAdvance\ThrottleManager.cs:line 17
   at TextAdvance.TextAdvance.TickSelectSkip() in C:\VS\TextAdvance\TextAdvance\TextAdvance.cs:line 360
at TextAdvance.TextAdvance.Tick(Framework framework) in C:\VS\TextAdvance\TextAdvance\TextAdvance.cs:line 220
[18:52]Attempted to read or write protected memory. This is often an indication that other memory is corrupt.   at ClickLib.Bases.ClickBase`2.ClickAddonList(PopupMenu* popupMenu, UInt16 index, EventType type) in C:\VS\TextAdvance\ClickLib\ClickLib\Bases\ClickBase{TImpl,TStruct}.cs:line 133
   at TextAdvance.ThrottleManager.Throttle(Action a, Int64 
delay) in C:\VS\TextAdvance\TextAdvance\ThrottleManager.cs:line 17
   at TextAdvance.TextAdvance.TickSelectSkip() in C:\VS\TextAdvance\TextAdvance\TextAdvance.cs:line 360
   at TextAdvance.TextAdvance.Tick(Framework framework) in C:\VS\TextAdvance\TextAdvance\TextAdvance.cs:line 220
[18:52]Attempted to read or write protected memory. This is often an indication that other memory is corrupt.   at 
ClickLib.Bases.ClickBase`2.ClickAddonList(PopupMenu* popupMenu, UInt16 index, EventType type) in C:\VS\TextAdvance\ClickLib\ClickLib\Bases\ClickBase{TImpl,TStruct}.cs:line 133
   at TextAdvance.ThrottleManager.Throttle(Action a, Int64 delay) in C:\VS\TextAdvance\TextAdvance\ThrottleManager.cs:line 17
   at TextAdvance.TextAdvance.TickSelectSkip() in C:\VS\TextAdvance\TextAdvance\TextAdvance.cs:line 360
at TextAdvance.TextAdvance.Tick(Framework framework) in C:\VS\TextAdvance\TextAdvance\TextAdvance.cs:line 220

**Comment by Eternita-S** [comment]
Please restart the game, you likely didn't do so for few hours and there was very recent Dalamud update that needs to be installed in order for this function to work. It should auto-update when restarting

**Comment by Ty0sMatic** [comment]
Derp..gotcha! Will try

**Comment by Ty0sMatic** [comment]
Yes that fixed it, thank you!
