### ISSUE TITLE
Operation is not valid error

### ISSUE THREAD

**Issue by rafflesiazero** [NightmareXIV/TextAdvance#42]
Hello! 

I noticed this issue crop up when I loaded TextAdvance after 7.1 was released: 

Operation is not valid due to the current state of the object.   at Lumina.Excel.RowRef`1.get_Value()
   at TextAdvance.TextAdvance.Tick() in D:\VS\TextAdvance\TextAdvance\TextAdvance.cs:line 241

I'm not sure if this is something on my end that I can fix or something that you need to work on, but I just wanted to let you know!

**Comment by Limiana** [comment]
This probably was an issue due to 7.1 update and should not happen anymore I think?
